/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/hitem3d.glb --output app/components/Hitem3d.js 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/hitem3d.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.tmp593hadh7obj.geometry}
        material={materials.pbr_material}
      />
    </group>
  );
}

useGLTF.preload("/hitem3d.glb");
