import localFont from "next/font/local";
import "./globals.css";
import Footer from "./components/layout/Footer";
import Header from "./components/layout/Header";

const satoshi = localFont({
  src: [
    {
      path: "../public/assets/fonts/satoshi/Satoshi-Light.ttf",
      weight: "300",
      style: "light",
    },
    {
      path: "../public/assets/fonts/satoshi/Satoshi-Regular.ttf",
      weight: "400",
      style: "regular",
    },
    {
      path: "../public/assets/fonts/satoshi/Satoshi-Medium.ttf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../public/assets/fonts/satoshi/Satoshi-Bold.ttf",
      weight: "600",
      style: "semibold",
    },
  ],
  variable: "--font-satoshi",
  display: "swap",
});

const birkenNue = localFont({
  src: [
    {
      path: "../public/assets/fonts/birken-nue/BirkenNue-Light.ttf",
      weight: "300",
      style: "light",
    },
    {
      path: "../public/assets/fonts/birken-nue/BirkenNue-Regular.ttf",
      weight: "400",
      style: "regular",
    },
    {
      path: "../public/assets/fonts/birken-nue/BirkenNue-Medium.ttf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../public/assets/fonts/birken-nue/BirkenNue-SemiBold.ttf",
      weight: "600",
      style: "semibold",
    },
    {
      path: "../public/assets/fonts/birken-nue/BirkenNue-Bold.ttf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-birkenNue",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${satoshi.variable} ${birkenNue.variable}`}>
        <Header />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
